# common
model_name: simpl

# global
g_num_modes: 6
g_obs_len: 50
g_pred_len: 60

# dataset
dataset: "simpl.av2_dataset:AV2Dataset" # 

# network
network: "simpl.simpl:Simpl"
init_weights: false
in_actor: 14
d_actor: 128
n_fpn_scale: 4
in_lane: 16
d_lane: 128
d_rpe_in: 5
d_rpe: 128
d_embed: 128
n_scene_layer: 4
n_scene_head: 8
dropout: 0.1
update_edge: true
param_out: "bezier"  # bezier/monomial/none
param_order: 7       # 7-th order polynomials

# loss
loss_fn: "simpl.av2_loss_fn:LossFunc"
cls_coef: 0.1
reg_coef: 0.9
mgn: 0.2
cls_th: 2.0
cls_ignore: 0.2
yaw_loss: true

# optimizer
opt: "adam"            # sgd/adam/adamw
weight_decay: 0.0
lr_scale_func: "none"  # none/sqrt/linear
scheduler: "polyline"  # cosine/cosine_warmup/step/polyline/none
init_lr: 1e-4
milestones: [0, 5, 35, 40]
values: [1e-4, 1e-3, 1e-3, 1e-4]

# eval
evaluator: "utils.evaluator:TrajPredictionEvaluator"
data_ver: "av2"
miss_thres: 2.0

